from flask import Flask, redirect, current_app, jsonify, url_for, render_template, Blueprint, request
import jwt
from datetime import datetime

program_details_ = Blueprint('program_details', __name__)

# Data untuk setiap materi
materi_data = {
    "1": {
        "judul": "Sesi 1 - Menjadi Sadar",
        "deskripsi": (
            "Menjadi Sadar berisi pengenalan tentang pelatihan mindfulness bagi mahasiswa, "
            "disusun dalam bentuk narasi dengan tokoh-tokoh yang mengeksplorasi dan "
            "mempraktikkan teknik mindfulness. Sesi ini juga menekankan manfaat latihan "
            "mindfulness secara teratur, dengan mendorong peserta untuk berlatih setiap hari "
            "guna meningkatkan konsentrasi, mengurangi stres, dan memperbaiki suasana hati. "
            "Program ini menyediakan panduan audio yang dapat diunduh serta ringkasan materi "
            "untuk mendukung praktik mandiri."
        ),
        "judul_audio1": "Audio Mindfulness Ruang Nafas 3 Menit",
        "audio1": "assets/audio panduan/Psidamai 1. 3 Min Breathing Space.mp3",
        "judul_audio2": "Audio Mindfulness Makan dengan Sadar",
        "audio2": "assets/audio panduan/Psidamai 1. Mindful Eating.mp3",
        "audio": [
            {"src": "assets/audio/sesi 1/1.1 Damai.mp3", "image": "assets/img/ilustrasi/sesi-1/Session 1.1.jpg", 
             "transkrip": [
                    {"time": 0, "text": "Hai, saya Damai"},
                    {"time": 2, "text": "Selamat Datang dalam sesi pertama pengenalan Mindfullness untuk mahasiswa!"},
                    {"time": 6, "text": "Program ini bertujuan untuk mempelajari keterampilan mindfulness dalam kehidupan sehari-hari."},
                    {"time": 11, "text": "Khususnya bagi mahasiswa."},
                    {"time": 13, "text": "Di dalamnya terdapat materi yang bisa diselesaikan dalam waktu 4 pekan."},
                    {"time": 17, "text": "Kamu akan mempelajari bagaimana mindfulness dapat dilatih."},
                    {"time": 21, "text": "Dengan mengikuti kisah seorang mahasiswa bernama Lisa."},
                    {"time": 24, "text": "Yang berlatih mindfulness untuk membantunya lebih baik dalam mengatasi tekanan psikologis yang dialami."},
                    {"time": 30, "text": "Di akhir sesi, terdapat ringkasan materi yang berisi konsep kunci dan latihan."},
                    {"time": 35, "text": "Yang tentunya bisa kamu unduh sehingga dapat dibaca kapanpun secara daring."},
                    {"time": 40, "text": "Terdapat juga rekaman audio yang dapat diunduh untuk didengarkan."},
                    {"time": 44, "text": "Yang akan membantumu dalam berlatih berbagai jenis latihan mindfulness."},
                    {"time": 48, "text": "Dan memandu untuk mengembangkan keterampilan mindfulness."}
            ]
            },
            {"src": "assets/audio/sesi 1/1.2 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-1/Session 1.2.jpg",
             "transkrip": [
                    {"time": 0, "text": "Halo, Aku Lisa"},
                    {"time": 3, "text": "Aku seorang mahasiswa di sebuah perguruan tinggi di ibukota."},
                    {"time": 6, "text": "Aku sekarang sedang menyelesaikan tugas akhir "},
                    {"time": 9, "text": "Sambil mengisi hari-hariku dengan kegiatan lain juga yang bermanfaat"},
                    {"time": 12, "text": "Saat ini, aku sangat menikmati kehidupanku sebagai mahasiswa."},
                    {"time": 17, "text": "Tapi"},
                    {"time": 18, "text": "Tahu kah kamu?"},
                    {"time": 20, "text": "Beberapa bulan sebelumnya,"},
                    {"time": 21, "text": "Kondisi psikologisku sangatlah jauh berbeda"},
                    {"time": 24, "text": "Dulu aku sering merasa cemas"},
                    {"time": 26, "text": "Sedih tanpa alasan yang jelas"},
                    {"time": 28, "text": "Bahkan sulit tidur. "},
                    {"time": 30, "text": "Namun.."},
                    {"time": 31, "text": "Semua itu berubah berkat latihan mindfulness"},
                    {"time": 34, "text": "Melalui latihan mindfulness"},
                    {"time": 36, "text": "Aku semakin banyak belajar bagaimana untuk bisa mencapai ketenangan dan kedamaian jiwa."},
                    {"time": 41, "text": "Dan di sini aku ingin membagi perjalananku berlatih mindfulness kepada kalian."}
            ]
             },
            {"src": "assets/audio/sesi 1/1.3 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-1/Session 1.3.jpg",
              "transkrip": [
                    {"time": 0, "text": "Dulu, aku hampir selalu cemas."},
                    {"time": 3, "text": "Terutama saat tugas-tugas perkuliahan menumpuk"},
                    {"time": 6, "text": "Aku merasa sangat tertekan"},
                    {"time": 9, "text": "Keadaan pun menjadi lebih sulit sejak setahun yang lalu..."},
                    {"time": 12, "text": "Ayah kehilangan pekerjaan dan kami mengalami masalah keuangan..."},
                    {"time": 16, "text": "Mereka semakin sering bertengkar."},
                    {"time": 19, "text": "Dan itu membuat aku sedih dan tidak tenang."},
                    {"time": 22, "text": "Ayah ibu terus menuntut agar aku cepat lulus"},
                    {"time": 25, "text": "Dan ini membuatku semakin tertekan."}
            ]
            },
            {"src": "assets/audio/sesi 1/1.4 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-1/Session 1.4.jpg",
             "transkrip": [
                    {"time": 0, "text": "Waktu sering kali berlalu dengan begitu saja.."},
                    {"time": 4, "text": "aku pun tidak dapat berkonsentrasi dan sering merasa tidak berguna.."},
                    {"time": 9, "text": "Aku juga mudah merasa lelah."},
                    {"time": 12, "text": "Namun anehnya, aku justru sulit untuk tidur."},
                    {"time": 15, "text": "Kepalaku sering terasa sakit, otot tegang, tapi tidak ada satu pun yang bisa meredakannya…"},
                    {"time": 23, "text": "Rasanya sangat gelisah,"},
                    {"time": 25, "text": "Mudah merasa marah..ingin melampiaskan pada orang-orang di sekitar…"},
                    {"time": 30, "text": "Aku merasa diriku buruk."}
            ]
            },
            {"src": "assets/audio/sesi 1/1.5 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-1/Session 1.5.jpg",
             "transkrip": [
                    {"time": 0, "text": "Suatu hari, saat kami pulang bersama setelah mengerjakan tugas"},
                    {"time": 4, "text": "Temanku Aisyah bertanya padaku"},
                    {"time": 7, "text": "Kenapa aku sering terlihat melamun dan kurang fokus."},
                    {"time": 11, "text": "Akupun bercerita"},
                    {"time": 12, "text": "Bahwa memang ada beberapa masalah yang sedang mengganggu pikiranku akhir-akhir ini."},
                    {"time": 18, "text": "Setelah mendengarkan ceritaku"},
                    {"time": 20, "text": "Aisyah kemudian bercerita bahwa dia dulu juga sempat mengalami tekanan psikologis,"},
                    {"time": 25, "text": "Namun terbantu dengan latihan mindfulness yang diberikan oleh seorang psikolog."},
                    {"time": 30, "text": "Dia pun menyarankanku untuk mulai mencari pertolongan kepada psikolog dan berlatih mindfulness"},
                    {"time": 36, "text": "Untuk membantu aku mengatasi apa yang sedang aku rasakan."}
            ]
            },
            {"src": "assets/audio/sesi 1/1.6 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-1/Session 1.6.jpg",
             "transkrip": [
                    {"time": 0, "text": "Awalnya aku masih ragu, tapi setelah mencari tahu lebih lanjut informasi mengenai mindfulness dari sosial media dan internet"},
                    {"time": 8, "text": "Aku jadi tertarik untuk mencobanya."},
                    {"time": 10, "text": "Aku akhirnya memutuskan untuk membuat janji dengan seorang psikolog di klinik kampus dengan keahlian di bidang mindfulness"},
                    {"time": 18, "text": "Namanya Pak Yudhis.."},
                    {"time": 20, "text": "Aku menyampaikan kepada Pak Yudhis keinginan untuk mulai berlatih mindfulness agar aku lebih bisa mengelola tekanan psikologis sehari-hari."},
                    {"time": 28, "text": "Pak Yudhis pun mulai jelaskan bagaimana mindfulness dapat membantu masalah yang sedang aku alami."},
                    {"time": 35, "text": "Menurut pak Yudhis, mindfulness memiliki tiga kualitas:"},
                    {"time": 39, "text": "Pertama. Memberi perhatian pada kondisi di sini dan saat ini"},
                    {"time": 43, "text": "Kedua. Mengenali dan menerimanya apa adanya"},
                    {"time": 47, "text": "Tiga. Bersikap lembut pada diri sendiri"},
                    {"time": 50, "text": "Saat kita mengalami stress atau tekanan, kita akan menjadi mudah tersinggung, tegang, khawatir, dan frustrasi."},
                    {"time": 58, "text": "Tanpa disadari, kita menjadi terjebak pada perasaan seperti itu"},
                    {"time": 62, "text": "Dan mulai menghakimi diri sebagai lemah, bodoh, bahkan tidak berharga."},
                    {"time": 66, "text": "Langkah pertama untuk berlatih mindfulness adalah dengan mengenali dan memahami bagaimana reaksi saat merasakan tekanan."},
                    {"time": 74, "text": "Jika tidak sadar bagaimana cara kita bereaksi terhadap suatu tekanan"},
                    {"time": 79, "text": "Maka seringkali yang muncul adalah respon yang tidak membantu"},
                    {"time": 82, "text": "Seperti marah-marah tidak jelas,"},
                    {"time": 84, "text": "Menangis terus menerus, dan sebagainya."},
                    {"time": 87, "text": "Melalui latihan mindfulness, aku pun diajarkan menjadi lebih sadar, terbuka, dan bersikap lembut pada diri sendiri"},
                    {"time": 95, "text": "Memberi perhatian pada kondisi di sini dan saat ini,"},
                    {"time": 99, "text": "Tidak terjebak pada pikiran dan perasaan"},
                    {"time": 101, "text": "Lebih menerima pengalaman, dan tidak reaktif terhadap hal itu"}
            ]
            },
            {"src": "assets/audio/sesi 1/1.7 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-1/Session 1.7.jpg",
             "transkrip": [
                    {"time": 0, "text": "Pak Yudhis pun mengajarkan padaku salah satu latihan dasar untuk mindfulness yang disebut sebagai “Ruang nafas 3 menit”."},
                    {"time": 7, "text": "Ia mengajarkanku untuk duduk tenang,"},
                    {"time": 10, "text": "Kemudian menutup mata jika merasa nyaman,"},
                    {"time": 11, "text": "Dan memberi perhatian pada nafas."},
                    {"time": 14, "text": "Dia menyampaikan bahwa berlatih mindfulness adalah dimulai dengan meyadari saat pikiran kita melayang-layang,"},
                    {"time": 21, "text": "lalu dengan lembut mengarahkannya kembali kepada situasi di sini dan saat ini melalui nafas."},
                    {"time": 27, "text": "Dia menjelaskan bahwa ini akan membantuku untuk memahami bagaimana rasanya memberi jeda dan perhatian pada saat ini. "},
                    {"time": 33, "text": "Aku pun mencoba mempraktikkannya."},
                    {"time": 36, "text": "Pada awalnya, aku kesulitan untuk berusaha fokus pada pernapasan."},
                    {"time": 41, "text": "Pikiranku melayang tak tentu arah."},
                    {"time": 44, "text": "Namun Pak Yudhis menyampaikan bahwa tidak ada cara yang benar atau salah dalam melakukan hal ini"},
                    {"time": 49, "text": "Saat aku tidak lagi fokus pada pernapasan"},
                    {"time": 52, "text": "aku hanya butuh untuk mengenali adanya pikiran yang muncul tanpa menghakimi"},
                    {"time": 57, "text": "dan dengan lembut membawa pikiran itu kembali pada suara dan sensasi pernapasan."},
                    {"time": 62, "text": "Untuk menjadi lebih mindful,"},
                    {"time": 65, "text": "Aku perlu berlatih mengembangkan rasa ingin tahu dan terbuka akan pikiran yang muncul"},
                    {"time": 69, "text": "Tanpa mengkritik"},
                    {"time": 71, "text": "Menyalahkan"},
                    {"time": 72, "text": "Ataupun merasa frustrasi akan hal itu."},
                    {"time": 75, "text": "Pak Yudhis mengarahkan"},
                    {"time": 76, "text": "Agar aku bisa berlatih ruang nafas 3 menit minimal 3 kali per hari."},
                    {"time": 81, "text": "Latihan ini akan mengajarkanku untuk menyadari dan mengenali berbagai pengalaman di sini dan saat ini."},
                    {"time": 87, "text": "Pak Yudhis bilang bahwa dengan latihan"},
                    {"time": 89, "text": "Aku akan bisa mengenali kapan saat mulai merasa tertekan atau cemas.."},
                    {"time": 94, "text": "Dengan menjadi lebih sadar akan apa yang terjadi pada pikiran"},
                    {"time": 97, "text": "Aku pun dapat belajar untuk melepaskan itu"},
                    {"time": 100, "text": "Dan kembali berfokus pada apa terjadi di sini dan saat ini."},
                    {"time": 104, "text": "Dia mengatakan bahwa aku bisa mengunduh"},
                    {"time": 107, "text": "Beberapa latihan terpandu yang dapat membantu dalam berlatih mindfulness."},
                    {"time": 113, "text": "Kemudian, Pak Yudhis mendorongku untuk berlatih mindfulness selama aktivitas sehari-hari"},
                    {"time": 118, "text": "Seperti saat makan"},
                    {"time": 120, "text": "Mandi, ataupun berpakaian."},
                    {"time": 122, "text": "Dia bilang bahwa itu akan membantuku sadar dan terlibat penuh dalam berbagai aktivitas sehari-hari"},
                    {"time": 128, "text": "Tanpa terus menerus terjebak pada pikiran yang dimiliki"},
                    {"time": 132, "text": "Dia juga mengajak untuk mengunduh beberapa latihan terpandu seperti"},
                    {"time": 135, "text": "‘Makan dengan sadar’ untuk memulainya."},
                    {"time": 138, "text": "Aku tahu ini tidak mudah tapi aku mau mencoba."}
            ]
            },
            {"src": "assets/audio/sesi 1/1.8 Damai.mp3", "image": "assets/img/ilustrasi/sesi-1/Session 1.8.jpg",
             "transkrip": [
                    {"time": 0, "text": "Hai, kamu sudah bertemu dengan Lisa dan awal dari perjalanannya berlatih mindfulness."},
                    {"time": 6, "text": "Mari menelaah kembali poin penting dari pembelajaran pada sesi ini."},
                    {"time": 9, "text": "Terkadang, hidup menjadi sangat sibuk dan menekan."},
                    {"time": 13, "text": "Ketika hal itu terjadi, kita seringkali menjalani hari-hari dengan dipenuhi oleh pikiran dan kekhawatiran"},
                    {"time": 20, "text": "Serta tidak dapat fokus penuh dengan yang kita kerjakan saat ini."},
                    {"time": 24, "text": "Kita juga cenderung untuk bertindak tanpa pikir panjang"},
                    {"time": 28, "text": "Tidak sadar mengenai apa yang sedang kita lakukan"},
                    {"time": 30, "text": "Dan mengapa kita melakukan hal tersebut."},
                    {"time": 33, "text": "Namun, saat kita berlatih menjadi lebih mindful"},
                    {"time": 37, "text": "Kita akan memahami pengalaman dengan cara yang berbeda."},
                    {"time": 41, "text": "Mindfulness adalah sebuah bentuk khusus memberi perhatian pada apa yang terjadi ‘di sini dan saat ini’, baik itu secara internal (seperti pikiran dan tubuh) atau eksternal (seperti lingkungan sekitar)."},
                    {"time": 55, "text": "Menjadi ‘sadar penuh’ artinya mengamati apa yang hadir dalam setiap momen dengan rasa ingin tahu"},
                    {"time": 61, "text": "Penuh perhatian dan penerimaan"},
                    {"time": 63, "text": "Serta tanpa menghakimi."},
                    {"time": 65, "text": "Mindfulness memiliki tiga kualitas utama:"},
                    {"time": 68, "text": "1. Memberi perhatian pada momen saat ini"},
                    {"time": 71, "text": "2. Mengenali dan menerima apa yang terjadi"},
                    {"time": 74, "text": "3. Bersikap lembut pada diri sendiri"},
                    {"time": 76, "text": "Latihan mindfulness diketahui memiliki banyak manfaat"},
                    {"time": 80, "text": "Bagi kesehatan dan kesejahteraan, termasuk meredakan stress"},
                    {"time": 84, "text": "Kecemasan"},
                    {"time": 85, "text": "Dan memperbaiki suasana hati"},
                    {"time": 87, "text": "Dengan berlatih mindfulness secara teratur"},
                    {"time": 90, "text": "Kamu akan belajar menjadi lebih hadir ‘di sini dan saat ini’"},
                    {"time": 94, "text": "Menjadi lebih toleran dan menerima pengalaman mereka"},
                    {"time": 97, "text": "Dan lebih bersikap baik terhadap diri mereka sendiri."},
                    {"time": 100, "text": "Mindfulness adalah sebuah keterampilan"},
                    {"time": 103, "text": "Dan seperti halnya keterampilan lainnya"},
                    {"time": 106, "text": "Mindfulness butuh untuk dilatih secara teratur."},
                    {"time": 109, "text": "Menjadi sadar artinya seperti menjadi orang yang penuh rasa ingin tahu yang secara berhati-hati mengamati apa yang terjadi di balik pikiran"},
                    {"time": 118, "text": "Pada tubuh dan lingkungan sekitar"},
                    {"time": 120, "text": "Serta bagaimana itu terkait satu sama lainnya"},
                    {"time": 123, "text": "Mindfuness bukanlah:"},
                    {"time": 124, "text": "- Sebuah cara untuk mengosongkan pikiran atau mendistraksi diri Kamu dari kenyataan "},
                    {"time": 130, "text": "- Strategi relaksasi "},
                    {"time": 131, "text": "- Kondisi supranatural"},
                    {"time": 133, "text": "- Cara untuk menghindari masalah, atau"},
                    {"time": 135, "text": "- Cara cepat dan ajaib untuk mengatasi kesulitan"},
                    {"time": 139, "text": "Mindfulness merupakan"},
                    {"time": 141, "text": "- Sebuah kondisi pikiran yang terbuka, sadar, dan penuh rasa ingin tahu"},
                    {"time": 146, "text": "- Sebuah keterampilan yang bisa dikuasai dengan latihan rutin"},
                    {"time": 149, "text": "- Sebuah bentuk perhatian dan kesadaran"},
                    {"time": 152, "text": "- Cara yang berbeda untuk menghadapi kesulitan dan masalah"},
                    {"time": 155, "text": "Serta Cara untuk hadir saat ini dan terlibat dalam berbagai aktivitas dalam hidup Kamu."},
                    {"time": 161, "text": "Mindfulness membutuhkan latihan secara berkala untuk membantumu memberi perhatian pada kondisi di sini dan saat ini."}
            ]
            },
            {"src": "assets/audio/sesi 1/1.9 Damai.mp3", "image": "assets/img/ilustrasi/sesi-1/Session 1.9.jpg",
             "transkrip": [
                    {"time": 0, "text": "Setelah kamu mengikuti kisah Lisa"},
                    {"time": 2, "text": "Sekarang saatnya kamu juga berlatih sendiri di rumah."},
                    {"time": 6, "text": "Pertama-tama, kami merekomendasikan kamu untuk mendengarkan rekaman audio"},
                    {"time": 11, "text": "Dimana instruktur akan memandu untuk melewati tahapan-tahapan latihan."},
                    {"time": 15, "text": "Namun demikian, apabila kamu sudah mulai terbiasa"},
                    {"time": 20, "text": "Kamu akan bisa memandu diri kamu sendiri melalui latihan mindfulness mandiri"},
                    {"time": 25, "text": "Sehingga kami menyarankan kamu berlatih tanpa rekaman suara"},
                    {"time": 28, "text": "Berlatih mindfulness adalah sebuah cara untuk melatih otakmu"},
                    {"time": 32, "text": "Dan ini memiliki manfaat yang positif"},
                    {"time": 34, "text": "Baik bagi kesehatan emosional maupun fisik."},
                    {"time": 38, "text": "Studi menunjukkan bahwa latihan mindfulness secara teratur akan membantu meningkatkan konsentrasi"},
                    {"time": 44, "text": "Menurunkan stress"},
                    {"time": 45, "text": "Kecemasan dan kekhawatiran"},
                    {"time": 47, "text": "Serta meningkatkan mood."},
                    {"time": 49, "text": "Untuk mendapatkan manfaat lebih banyak"},
                    {"time": 51, "text": "Menjadi penting untuk melatihnya setiap hari"},
                    {"time": 54, "text": "Dan kami menyarankan untuk mengusahakan agar jangan sampai ada dua hari berlalu tanpa latihan mindfulness. "},
                    {"time": 61, "text": "Ingat, latihan dalam bentuk apa pun lebih baik dibandingkan tidak sama sekali"},
                    {"time": 67, "text": "Dan tidak ada cara yang benar dan salah dalam berlatih."},
                    {"time": 71, "text": "Pada sesi selanjutnya, kamu akan mengikuti Lisa saat belajar dan berlatih keterampilan mindfulness baru "},
                    {"time": 77, "text": "Dan mengatasi kesulitan umum yang dirasakan dengan mindfulness"},
                    {"time": 82, "text": "Kami paham bahwa mungkin akan sulit untuk menemukan waktu"},
                    {"time": 85, "text": "Untuk itu, kami menyertakan juga"},
                    {"time": 87, "text": "‘Jurnal Latihan Mindfulness Harian’ dan daftar ‘Aktivitas Harian dengan Penuh Kesadaran’"},
                    {"time": 92, "text": "Di dalam ringkasan pembelajaran untuk membantumu berlatih mindfulness setiap harinya."},
                    {"time": 98, "text": "Selamat! Ini adalah akhir dari materi pertama."},
                    {"time": 100, "text": "Silakan unduh dokumen ringkasan materi dan audio mindfulness untuk mulai berlatih."},
                    {"time": 105, "text": "Materi kedua akan tersedia dalam jangka waktu lima hari dari saat ini"},
                    {"time": 109, "text": "Dan kamu bisa memulai materi kedua dalam jangka waktu 7 hari ke depan"},
                    {"time": 113, "text": "Terima kasih sudah mengikuti sesi ini."},
                    {"time": 116, "text": "Kami berharap kamu menemukan latihan mindfulness yang digambarkan dalam sesi ini menjadi sesuatu yang menarik dan bermanfaat."},
                    {"time": 123, "text": "Jangan ragu untuk menghubungi kami jika kamu ada pertanyaan."},
                    {"time": 127, "text": "Sampai berjumpa di sesi selanjutnya!"}
            ]
            },
        ],
        "naskah": "assets/ringkasan_materi/Ringkasan Sesi 1 - Psidamai.pdf"
    },
    "2": {
        "judul": "Sesi 2 - Memahami Pikiran Kamu",
        "deskripsi": (
            "Memahami Pikiran Kamu melanjutkan pelajaran mindfulness bagi mahasiswa, dengan "
            "fokus pada latihan mengenali pikiran dan pengembangan kesadaran diri. Pada sesi ini, "
            "Damai sebagai narator mengingatkan peserta untuk menerapkan mindfulness dengan cara "
            "memperhatikan pikiran, perasaan, dan sensasi yang hadir tanpa menghakimi. Selain itu, "
            "sesi ini memperkenalkan latihan 'Mindfulness dalam Bernafas' dan 'Mindful Stretching.' "
            "Latihan ini bertujuan untuk membantu peserta mengembangkan kemampuan untuk menghadapi "
            "berbagai perasaan dan pikiran dengan lebih terbuka."
        ),
        "judul_audio1": "Audio Mindfulness  dalam bernafas",
        "audio1": "assets/audio panduan/Psidamai 2. Mindful Breathing.mp3",
        "judul_audio2": "Audio Latihan Mindful Stretching",
        "audio2": "assets/audio panduan/Psidamai 2. Mindful Stretching.mp3",
        "audio": [
            {"src": "assets/audio/sesi 2/2.1 Damai.mp3", "image": "assets/img/ilustrasi/sesi-2/Session 2.1.jpg",
             "transkrip": [
                    {"time": 0, "text": "Hai, bertemu lagi dengan saya Damai."},
                    {"time": 2, "text": "Selamat datang di Materi 2 dari Perkenalan Mindfulness untuk Mahasiswa."},
                    {"time": 7, "text": "Senang bertemu denganmu lagi!"},
                    {"time": 9, "text": "Kami harap kamu sudah meluangkan waktu di minggu lalu"},
                    {"time": 12, "text": "Untuk membaca ringkasan materi dan berlatih mindfulness dalam keseharian."},
                    {"time": 16, "text": "Sebelumnya, mari kita bahas kembali apa yang telah dipelajari di Materi 1"},
                    {"time": 21, "text": "Di Materi 1, kamu telah mempelajari bahwa"},
                    {"time": 25, "text": "Menjadi mindful adalah memberi perhatian secara penuh terhadap segala sesuatu yang terjadi."},
                    {"time": 31, "text": "Termasuk di dalamnya memberikan perhatian kepada pikiran"},
                    {"time": 34, "text": "Perasaan"},
                    {"time": 36, "text": "Dan sensasi yang Kamu alami dengan cara tertentu"},
                    {"time": 39, "text": "Dengan keterbukaan"},
                    {"time": 41, "text": "Rasa ingin tahu"},
                    {"time": 43, "text": "Dan tanpa menghakimi pengalaman tersebut sebagai pengalaman baik atau buruk."},
                    {"time": 47, "text": "Latihan mindfulness dapat membantu kamu memusatkan perhatian pada hal-hal yang penting, yang sedang terjadi saat ini."},
                    {"time": 55, "text": "Latihan tersebut membantu kamu untuk menjadi lebih sadar akan reaksi kamu"},
                    {"time": 60, "text": "Dan juga dapat membantu untuk menghindari agar tidak terjebak di dalam pikiran dan perasaan."},
                    {"time": 66, "text": "Mari lihat bagaimana Lisa mencoba berlatih mindfulness."}
            ]
            },
            {"src": "assets/audio/sesi 2/2.2 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-2/Session 2.2.jpg",
             "transkrip": [
                    {"time": 1, "text": "Seperti yang disampaikan oleh Pak Yudhis"},
                    {"time": 3, "text": "Aku mencoba untuk melakukan latihan Ruang Bernafas 3 Menit"},
                    {"time": 8, "text": "Setidaknya tiga kali sehari..."},
                    {"time": 11, "text": "Awalnya terasa aneh..."},
                    {"time": 14, "text": "Sepertinya salah..."},
                    {"time": 17, "text": "Duh, kenapa jadi berpikir terus.."},
                    {"time": 19, "text": "Aku kayanya ga ada waktu untuk ini.. "},
                    {"time": 24, "text": "Ternyata latihan tersebut sulit dilakukan"},
                    {"time": 28, "text": "Dan aku pun awalnya merasa patah semangat."},
                    {"time": 32, "text": "Sulit rasanya untuk berhenti dan cukup duduk diam"},
                    {"time": 35, "text": "Meskipun itu hanya untuk beberapa menit!"},
                    {"time": 39, "text": "Aku merasa sangat gelisah... "},
                    {"time": 42, "text": "Berfokus pada pernafasan membuatku lebih jadi khawatir"},
                    {"time": 46, "text": "Mengenai ketidakmampuan untuk bernafas dengan benar."},
                    {"time": 49, "text": "Tenang, ga boleh panik.."},
                    {"time": 52, "text": "Akan berhasil gak yaa...?"},
                    {"time": 55, "text": "Hmm, kenapa sulit sekali...?"},
                    {"time": 59, "text": "Aku pun menunda untuk berlatih mindfulness.."},
                    {"time": 62, "text": "Terdapat banyak sekali gangguan.."},
                    {"time": 65, "text": "Aku sibuk sekarang, tidak punya waktu untuk latihan..."},
                    {"time": 69, "text": "Aku berusaha berlatih mindfulness lagi"},
                    {"time": 72, "text": "Namun setiap kali aku berniat mencobanya, selalu ada yang mengganggu."},
                    {"time": 78, "text": "Tapi kemudian"},
                    {"time": 81, "text": "Aku akhirnya teringat akan apa yang Pak Yudhis katakan mengenai mindfulness."},
                    {"time": 86, "text": "Mindfulness adalah tentang mengamati pikiran"},
                    {"time": 90, "text": "Tanpa harus memberikan reaksi terhadapnya"},
                    {"time": 94, "text": "Aku sadar"},
                    {"time": 95, "text": "Meskipun pikiran-pikiran yang muncul dalam benakku memberi tahu bahwa tidak ada waktu untuk berlatih hal baru"},
                    {"time": 101, "text": "Aku dapat memilih"},
                    {"time": 103, "text": "Untuk tidak mengikuti apa yang aku pikirkan."},
                    {"time": 106, "text": "Aku bisa meluangkan waktu beberapa menit waktu luang untuk berlatih"}
            ]
            },
            {"src": "assets/audio/sesi 2/2.3 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-2/Session 2.3.jpg",
             "transkrip": [
                    {"time": 0, "text": "Jadi aku pun memutuskan untuk pelan-pelan saja"},
                    {"time": 4, "text": "Dan mencoba berlatih tanpa rekaman kapanpun memiliki waktu luang..."},
                    {"time": 10, "text": "Satu..."},
                    {"time": 13, "text": "Dua...."},
                    {"time": 15, "text": "Aku mencoba untuk berlatih menghitung nafas saat berlatih."},
                    {"time": 19, "text": "Berhitung membantu untuk kembali fokus pada nafas"},
                    {"time": 22, "text": "ketika pikiran-pikiran mulai muncul ke dalam benakku.."},
                    {"time": 26, "text": "Aku memutuskan untuk mencoba dan menjadwalkan latihan mindfulness di waktu luang..."},
                    {"time": 32, "text": "Tidak perlu untuk menghakimi…"},
                    {"time": 35, "text": "Tarik nafas…"},
                    {"time": 37, "text": "Aku akan coba sebaik mungkin.."},
                    {"time": 40, "text": "Hembuskan nafas.."},
                    {"time": 42, "text": "(Lisa sedang menghembuskan nafas)"},
                    {"time": 44, "text": "Aku juga mengatur alarm pengingat di telfon genggam"},
                    {"time": 47, "text": "Untuk membantu latihan setiap harinya"},
                    {"time": 50, "text": "Selain latihan ruang nafas"},
                    {"time": 53, "text": "Melakukan aktivitas rutin di sepanjang hari dengan mindful juga membantu."},
                    {"time": 59, "text": "Meski cukup sulit pada awalnya"},
                    {"time": 61, "text": "Aku memulai dengan beberapa aktivitas sederhana."},
                    {"time": 64, "text": "Contohnya saat makan seperti ini."},
                    {"time": 67, "text": "Aku mengamati dengan baik apa yang akan aku makan"},
                    {"time": 71, "text": "Menyadari bagaimana makanan ini bisa sampai padaku"},
                    {"time": 75, "text": "Merasakan tekstur dan aromanya dengan penuh kesadara"},
                    {"time": 79, "text": "Dan mengunyahnya perlahan hingga dia masuk ke tenggorokan."},
                    {"time": 84, "text": "Aku ingat Aisyah pernah bercerita bahwa dia juga mempraktikkan mindfulness saat sedang sholat."},
                    {"time": 91, "text": "Menurutnya mindfulness membantu untuk lebih bisa khusyuk dalam beribadah."},
                    {"time": 96, "text": "Mungkin aku akan mencobanya juga."},
                    {"time": 98, "text": "Meskipun tidak mudah"},
                    {"time": 100, "text": "Melakukan aktivitas secara mindful akan membantuku untuk bisa terlibat secara penuh"},
                    {"time": 105, "text": "Dalam melakukan sesuatu dan terhubung dengan pengalaman di masa kini"},
                    {"time": 109, "text": "Sehingga tidak terperangkap dalam pikiran-pikiran yang mengganggu."}
            ]
            },
            {"src": "assets/audio/sesi 2/2.4 Damai.mp3", "image": "assets/img/ilustrasi/sesi-2/Session 2.4.jpg",
             "transkrip": [
                    {"time": 0, "text": "Hai, kamu tadi sudah melihat bagaimana Lisa mencoba mempraktikkan latihan ruang nafas tiga menit"},
                    {"time": 7, "text": "Dan menerapkan mindfulness dalam kesehariannya."},
                    {"time": 9, "text": "Kami menganjurkan untuk terus melakukan latihan-latihan ini setiap hari"},
                    {"time": 14, "text": "Namun jika belum berhasil membuat latihan rutin"},
                    {"time": 17, "text": "Tetap ingat untuk bersikap baik pada dirimu sendiri."},
                    {"time": 20, "text": "Ingat, menggunakan mindfulness bukan merupakan strategi pengalihan"},
                    {"time": 26, "text": "Mindfulness bukan tentang mengabaikan apa yang sedang terjadi pada dirimu"},
                    {"time": 30, "text": "Terus menerus memikirkan apa yang telah lalu"},
                    {"time": 33, "text": "Atau terjebak pada kekhawatiran. "},
                    {"time": 36, "text": "Mindfulness adalah tentang melepaskan diri dari belenggu pengalaman-pengalaman yang tidak diinginkan"},
                    {"time": 42, "text": "Atau tidak diharapkan dan menjalani hidup secara penuh"},
                    {"time": 45, "text": "Pada setiap momen di satu waktu."},
                    {"time": 48, "text": "Mindfulness adalah tentang mengembangkan sikap baik dan welas asih kepada diri sendiri dan pengalamanmu."},
                    {"time": 54, "text": "Memupuk mindfulness membantu kamu untuk menghadapi"},
                    {"time": 58, "text": "Menoleransi"},
                    {"time": 60, "text": "Dan mengatasi berbagai pengalaman tanpa merasa kewalahan"},
                    {"time": 63, "text": "Dan kehabisan energi karenanya."},
                    {"time": 66, "text": "Menggunakan nafas sebagai jangkar terhadap masa kini"},
                    {"time": 69, "text": "Adalah salah satu keterampilan dasar mindfulness."},
                    {"time": 73, "text": "Di materi ini, kamu akan belajar bagaimana untuk melatih keterampilan mindfulness"},
                    {"time": 78, "text": "Yang dinamakan Mindfulness dalam Bernafas."},
                    {"time": 83, "text": "Latihan ini akan membantumu untuk terus mengembangkan keterampilan dalam menyadari"},
                    {"time": 87, "text": "Mendeskripsikan"},
                    {"time": 88, "text": "Mengamati"},
                    {"time": 89, "text": "Dan menghadirkan pengalaman saat ini dengan rasa ingin tahu dan tanpa penilaian."},
                    {"time": 95, "text": "Rekaman suara untuk memandu Mindfulness dalam Bernafas"},
                    {"time": 98, "text": "Akan membantu dalam memusatkan perhatianmu pada nafas"},
                    {"time": 102, "text": "Sambil mengamati pengalaman-pengalaman lainnya"},
                    {"time": 104, "text": "Seperti perasaan dan sensasi datang dan pergi."},
                    {"time": 108, "text": "Mari kita lihat bagaimana Lisa berlatih keterampilan ini.."}
            ]
            },
            {"src": "assets/audio/sesi 2/2.5 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-2/Session 2.5.jpg",
             "transkrip": [
                    {"time": 0, "text": "Saat pertama kali duduk untuk mencoba Mindfulness dalam Bernafas"},
                    {"time": 4, "text": "Aku menemukan bahwa hampir mustahil untukku bisa duduk diam."},
                    {"time": 9, "text": "Aku merasa tegang dan gelisah dan langsung menyerah."},
                    {"time": 14, "text": "Aku sudah mendengar banyak hal positif tentang mindfulness"},
                    {"time": 18, "text": "Dan aku hanya perlu bersabar pada diriku sendiri"},
                    {"time": 21, "text": "Kata-kata Pak Yudhis terngiang di kepalaku:"},
                    {"time": 25, "text": "Lakukan dengan perlahan, bersikaplah lembut pada diri sendiri.."},
                    {"time": 31, "text": "Jadi, aku memutuskan untuk berlatih Ruang Nafas 3 Menit beberapa kali"},
                    {"time": 36, "text": "Hingga aku merasa lebih percaya diri untuk melakukan mindfulness dalam bernafas."},
                    {"time": 41, "text": "Setelah itu, aku pun mulai siap"},
                    {"time": 45, "text": "Untuk mencoba meditasi Mindfulness dalam Bernafas yang lebih lama lagi..."},
                    {"time": 50, "text": "...menjadi lebih mudah untuk terus kembali pada nafas"},
                    {"time": 53, "text": "Ketika kekhawatiran dan pikiran-pikiran muncul!"},
                    {"time": 59, "text": "Aku pun mulai ‘menyadari’ kapan pikiran-pikiran memasuki benakku"},
                    {"time": 63, "text": "Dan semakin aku berlatih"},
                    {"time": 66, "text": "Semakin menjadi lebih mudah untuk sekedar mengamatinya"},
                    {"time": 69, "text": "Tanpa harus bereaksi dengan perasaan frustrasi..."},
                    {"time": 74, "text": "Hmm.. Jam berapa ini? Aku ada janji mengerjakan tugas kelompok."},
                    {"time": 79, "text": "Nah kan, ada pikiran yang muncul!"}
            ]
            },
            {"src": "assets/audio/sesi 2/2.6 Damai.mp3", "image": "assets/img/ilustrasi/sesi-2/Session 2.6.jpg",
             "transkrip": [
                    {"time": 0, "text": "Pengalaman Lisa adalah hal yang sangat umum terjadi."},
                    {"time": 4, "text": "Jika kamu menemukan bahwa mencoba latihan mindfulness yang baru terasa sulit"},
                    {"time": 8, "text": "Bersikaplah sabar dan lembut pada diri sendiri."},
                    {"time": 12, "text": "Banyak orang menemukan bahwa cukup sulit untuk mengalihkan dan mempertahankan"},
                    {"time": 16, "text": "Perhatian mereka dalam waktu yang lama."},
                    {"time": 18, "text": "Ini sangat wajar dan karena ini adalah keterampilan"},
                    {"time": 21, "text": "Ini akan berkembang melalui latihan."},
                    {"time": 24, "text": "Latihan mindfulness lain yang dapat membantu"},
                    {"time": 27, "text": "Di saat-saat dimana tubuh terasa sangat tegang atau nyeri dinamakan Mindful Stretching."},
                    {"time": 33, "text": "Mindful Stretching mengajarkan untuk memusatkan perhatian pada pergerakan dari tubuh."},
                    {"time": 38, "text": "Terkadang lebih mudah untuk memusatkan diri terhadap peregangan tubuh daripada terhadap nafas."},
                    {"time": 44, "text": "Mindful stretching dapat digunakan sebagai sebuah latihan mindfulness yang berdiri sendiri"},
                    {"time": 49, "text": "Atau dilakukan sebelum latihan mindfulness formal"},
                    {"time": 52, "text": "Seperti Mindfulness dalam Bernafas"},
                    {"time": 55, "text": "Untuk membantu pikiran dan tubuh menyesuaikan diri dan menjadi lebih santai."},
                    {"time": 59, "text": "Oke, kita sudah akan mengakhiri materi kedua dari Pengenalan Mindfulness untuk Mahasiswa. "},
                    {"time": 64, "text": "Jangan lupa untuk mengunduh ringkasan materi"},
                    {"time": 67, "text": "Lembar kerja, dan rekaman audio di akhir materi."}
            ]
            },
            {"src": "assets/audio/sesi 2/2.7 Damai.mp3", "image": "assets/img/ilustrasi/sesi-2/Session 2.7.jpg",
             "transkrip": [
                    {"time": 0, "text": "Mari simpulkan poin-poin penting dari materi kali ini."},
                    {"time": 4, "text": "Di Materi ini, kamu telah belajar mengenai latihan mindfulness yang dinamakan"},
                    {"time": 8, "text": "Mindfulness dalam Bernafas."},
                    {"time": 10, "text": "Tujuan dari latihan mindfulness bukanlah untuk memiliki pikiran yang kosong"},
                    {"time": 16, "text": "Dan bukan untuk ‘menepis’ pikiran yang muncul."},
                    {"time": 19, "text": "Namun, latihan ini akan membantu dalam menyadari"},
                    {"time": 23, "text": "Kapan pikiran itu muncul dalam benak kita"},
                    {"time": 26, "text": "Menamai apa yang memenuhi pikiran kita"},
                    {"time": 28, "text": "Lalu membawa kembali pikiran pada nafas"},
                    {"time": 32, "text": "Seperti halnya yang dialami oleh Lisa, mungkin ini akan terasa sulit di awal"},
                    {"time": 37, "text": "Dan kamu bisa saja cepat merasa patah semangat."},
                    {"time": 40, "text": "Tapi tenang, kesulitan dalam latihan adalah pengalaman yang wajar."},
                    {"time": 46, "text": "Ingat, berlatih mindfulness artinya melatih ulang pikiran kita"},
                    {"time": 51, "text": "Sehingga kita lebih bisa memiliki kendali terhadapnya"},
                    {"time": 54, "text": "Ini butuh waktu dan usaha untuk menguasainya."},
                    {"time": 57, "text": "Untuk membantu pikiran dan tubuh menyesuaikan diri ke dalam latihan"},
                    {"time": 61, "text": "Cobalah untuk menggunakan latihan Mindful Stretching."},
                    {"time": 64, "text": "Mindful Stretching mengajarkan untuk memusatkan perhatian pada pergerakan dari tubuh"},
                    {"time": 69, "text": "Yang mana kadangkala lebih mudah untuk memusatkan diri terhadapnya daripada terhadap nafas"},
                    {"time": 75, "text": "Ingatlah untuk membuat jadwal latihan"},
                    {"time": 78, "text": "Berlatih setidaknya 10-20 menit per hari"},
                    {"time": 81, "text": "Dan jangan lewatkan dua hari berturut-turut tanpa latihan."},
                    {"time": 86, "text": "Untuk tahap awal, gunakan rekaman audio yang sudah kami sediakan untuk membantu."},
                    {"time": 91, "text": "Setelahnya, kamu bisa mencoba berlatih tanpa ada panduan."},
                    {"time": 95, "text": "Pada Ringkasan Materi kami juga sudah meringkas ‘Kesulitan umum dalam berlatih mindfulness’"},
                    {"time": 101, "text": "Bersama dengan saran-saran tentang bagaimana untuk mengatasinya."},
                    {"time": 104, "text": "Jadi, pastikan bahwa kamu mengunduh dan membaca bagian Ringkasan Materi"},
                    {"time": 109, "text": "Serta mendengarkan rekaman audio mindfulness untuk berlatih."},
                    {"time": 113, "text": "Terima kasih telah mengikuti Materi 2."},
                    {"time": 114, "text": "Sampai bertemu di Materi 3!"}
            ]
            },
        ],
        "naskah": "assets/ringkasan_materi/Ringkasan Sesi 2 - Psidamai.pdf"
    },
    "3": {
        "judul": "Sesi 3 - Mengenali Hambatan dan Mendengarkan Tubuh",
        "deskripsi": 
            """Mengenali hambatan dan mendengarkan tubuh: "Mengenali Hambatan dan Mendengarkan Tubuh" melanjutkan pelajaran mindfulness dengan fokus pada identifikasi hambatan-hambatan umum dalam latihan mindfulness dan cara mendengarkan tubuh.
        Pada sesi ini, memperkenalkan latihan Body Scan dan Mindful Walking. Latihan Body Scan membantu peserta untuk fokus pada berbagai sensasi tubuh, sehingga bisa mengenali ketegangan fisik dan merelaksasinya secara bertahap. Sedangkan, Mindful Walking bertujuan melatih peserta agar lebih sadar dan hadir dalam setiap langkah, mengamati perasaan dan gerakan tubuh mereka.
        Peserta dianjurkan untuk melatih kedua teknik ini secara rutin, dimulai dengan rekaman audio sebagai panduan. Diharapkan, melalui latihan-latihan ini, peserta dapat lebih memahami tubuh dan pikirannya, serta lebih mampu menghadapi tantangan sehari-hari dengan tenang dan penuh kesadaran.""",
        "judul_audio1": "Audio Mindfulness Pemindaian Tubuh",
        "audio1": "assets/audio panduan/Psidamai 3. Body Scan.mp3",
        "judul_audio2": "Audio Mindfulness Berjalan dengan Penuh Kesadaran",
        "audio2": "assets/audio panduan/Psidamai 3. Mindful Walking.mp3",
        "audio": [
            {"src": "assets/audio/sesi 3/3.1 Damai dan Lisa.mp3", "image": "assets/img/ilustrasi/sesi-3/Ilustrasi 3.1.jpg",
             "transkrip": [
                    {"time": 0, "text": "Selanjutnya"},
                    {"time": 1, "text": "Dalam materi ini kamu akan belajar tentang"},
                    {"time": 5, "text": "Mendengarkan tubuhmu dan memusatkan perhatian"},
                    {"time": 8, "text": "Pada berbagai sensasi berbeda yang datang dan pergi di area tubuh."},
                    {"time": 13, "text": "Latihan mindfulness yang akan kita fokuskan adalah"},
                    {"time": 17, "text": "Body Scan atau pemindaian tubuh dan mindful waking atau berjalan dengan penuh kesadaran"},
                    {"time": 23, "text": "Sambil mempraktikan latihan-latihan ini"},
                    {"time": 26, "text": "Sadari pikiran"},
                    {"time": 27, "text": "Perasaan"},
                    {"time": 28, "text": "Dan sensasi apa yang timbul ketika sebuah hambatan atau halangan muncul dalam pengalamanmu berlatih."},
                    {"time": 35, "text": "Mari lihat bagaimana Lisa belajar menggunakan teknik ini."},
                    {"time": 40, "text": "Aku menemukan bahwa tidurku menjadi lebih baik kualitasnya."},
                    {"time": 44, "text": "Aku pun menjadi lebih mudah untuk menyadari dan melepaskan diri"},
                    {"time": 48, "text": "Dari pikiran berulang yang mengganggu.."},
                    {"time": 50, "text": "Aku mulai merasa lebih hadir"},
                    {"time": 52, "text": "Dan terlibat dengan orang-orang penting di hidupku"},
                    {"time": 55, "text": "Dan mereka menyadarinya juga."},
                    {"time": 57, "text": "Aku pun menjadi lebih nyaman dalam berinteraksi dengan mereka.."},
                    {"time": 60, "text": "Permasalahan dan kesulitan hidup memang masih muncul.."},
                    {"time": 64, "text": "Saat itu terjadi, aku seringkali masih merasa sedih dan bahkan kewalahan..."},
                    {"time": 69, "text": "Namun, perasaan-perasaan tersebut tidak lagi bertahan lama seperti dulu.."},
                    {"time": 74, "text": "Aku sudah belajar mengakui perasaan yang aku miliki"},
                    {"time": 78, "text": "Tanpa harus terus terlarut di dalamnya.."},
                    {"time": 80, "text": "Meski kadang berlatih mindfulness terasa sulit"},
                    {"time": 83, "text": "Aku selalu punya pilihan untuk menyesuaikan diri dan berusaha terlibat penuh"},
                    {"time": 88, "text": "Dalam hari-hariku, dan semuanya sudah terasa sangat membantu.."}
            ]
            },
            {"src": "assets/audio/sesi 3/3.2 Damai.mp3", "image": "assets/img/ilustrasi/sesi-3/Ilustrasi 3.2.jpg",
             "transkrip": [
                    {"time": 0, "text": "Latihan mindfulness memang merupakan hal yang menantang."},
                    {"time": 5, "text": "Dan dalam materi kali ini, kamu akan belajar mengenai"},
                    {"time": 9, "text": "Lima penghalang atau ‘hambatan’ umum dalam berlatih mindfulness."},
                    {"time": 13, "text": "Kamu juga akan belajar untuk mengenali kapan hambatan-hambatan ini muncul"},
                    {"time": 18, "text": "Dan bagaimana mereka mempengaruhi dirimu, bukan hanya dalam latihan mindfulness"},
                    {"time": 24, "text": "Tapi juga mempengaruhi pengalaman lain dalam hidupmu."},
                    {"time": 27, "text": "Terdapat lima penghalang atau ‘hambatan’ umum dalam berlatih mindfulness.."},
                    {"time": 32, "text": "Pertama dalah desire atau hasrat"},
                    {"time": 35, "text": "Kedua adalah aversion atau keengganan"},
                    {"time": 38, "text": "Ketiga adalah rasa kantuk"},
                    {"time": 40, "text": "Keempat adalah kegelisahan"},
                    {"time": 42, "text": "Dan kelima adalah keraguan"},
                    {"time": 45, "text": "Mari kita bahas satu per satu."},
                    {"time": 47, "text": "Pertama adalah desire (hasrat)"},
                    {"time": 51, "text": "Yaitu adanya pikiran atau perasaan ‘menginginkan’ agar sesuatu menjadi berbeda dari keadaan saat ini."},
                    {"time": 58, "text": "Sebenarnya, ini sesuatu yang benar-benar wajar dan pengalaman yang biasa dialami."},
                    {"time": 64, "text": "Meskipun begitu, dengan tidak menyadari ketika hasrat ini muncul"},
                    {"time": 69, "text": "Dapat membuat kamu terjebak dalam pengalaman tersebut"},
                    {"time": 72, "text": "Dan terperangkap dalam perasaan frustrasi, kekecewaan, kemarahan, dan kebencian"},
                    {"time": 79, "text": "Khususnya bila hasrat itu tidak bisa tercapai."},
                    {"time": 83, "text": "Kedua adalah aversion atau keengganan"},
                    {"time": 86, "text": "Yaitu adanya pikiran dan perasaan untuk bersikap ‘resisten’ atau enggan dalam menjalani sesuatu yang harus dijalani saat ini."},
                    {"time": 94, "text": "Sebenarnya, perasaan marah atau frustrasi"},
                    {"time": 98, "text": "ingin untuk berhenti, atau menyerah dalam menjalani sesuatu yang sulit"},
                    {"time": 103, "text": "Termasuk dalam berlatih mindfulness, adalah hal yang wajar..."},
                    {"time": 108, "text": "Jadi ini bukanlah kesalahan.."},
                    {"time": 110, "text": "Namun, kamu perlu menyadari ini sebagai salah satu bentuk pasang surut"},
                    {"time": 115, "text": "Dari berbagai emosi dan motivasi yang kita rasakan."},
                    {"time": 119, "text": "Dan bahwa perasaan yang kita rasakan akan surut seiring dengan berjalannya waktu."}
            ]
             },
            {"src": "assets/audio/sesi 3/3.3 Damai.mp3", "image": "assets/img/ilustrasi/sesi-3/Ilustrasi 3.3.jpg",
             "transkrip": [
                    {"time": 0, "text": "Ketiga adalah rasa kantuk, yaitu perasaan lesu yang disertai dengan kondisi mental yang kurang waspada."},
                    {"time": 9, "text": "Hal ini bisa timbul dari kelelahan fisik"},
                    {"time": 12, "text": "Atau keengganan terhadap apa yang harus dijalani di masa kini."},
                    {"time": 16, "text": "Kamu perlu menyadari kapan dan dimana rasa kantuk ini muncul.."},
                    {"time": 21, "text": "Jika kamu bisa mengenali sumbernya"},
                    {"time": 24, "text": "Kamu dapat mengatur..dimana, kapan, dan bagaimana kamu mempraktikkan mindfulness."},
                    {"time": 31, "text": "Keempat adalah kegelisahan, yang muncul dalam bentuk pergolakan mental."},
                    {"time": 36, "text": "Hal tersebut dapat timbul karena keengganan, cedera fisik, atau dari hasrat untuk segera mengubah situasi."},
                    {"time": 44, "text": "Dengan menyadari sumber kegelisahan yang muncul"},
                    {"time": 47, "text": "Kamu dapat membuat penyesuaian pada bagaimana kamu mempraktikkan mindfulness."},
                    {"time": 53, "text": "Terakhir adalah keraguan, yaitu munculnya ketidakyakinan"},
                    {"time": 57, "text": "Dan bertanya-tanya apakah kamu melakukan mindfulness dengan ‘benar’."},
                    {"time": 61, "text": "Hal tersebut dapat muncul dari pikiran-pikiran seperti"},
                    {"time": 65, "text": "“Apakah aku melakukannya dengan benar?” atau “Aku seharusnya selalu berpikiran positif”."},
                    {"time": 72, "text": "Ketika hambatan-hambatan ini muncul, ingat untuk bersikaplah lemah lembut"},
                    {"time": 77, "text": "Penuh rasa ingin tahu, dan welas asih terhadap berbagai pikiran dan pengalaman yang ada"},
                    {"time": 82, "text": "Terutama untuk kesulitan-kesulitan yang telah kamu hadapi di dalam latihan mindfulness."}
            ]
            },
            {"src": "assets/audio/sesi 3/3.4 Damai dan Lisa.mp3", "image": "assets/img/ilustrasi/sesi-3/Ilustrasi 3.4.jpg",
             "transkrip": [
                    {"time": 0, "text": "Selanjutnya,..dalam materi ini kamu akan belajar tentang"},
                    {"time": 5, "text": "Mendengarkan tubuhmu dan memusatkan perhatian pada berbagai sensasi berbeda"},
                    {"time": 10, "text": "Yang datang dan pergi di area tubuh.."},
                    {"time": 13, "text": "Latihan mindfulness yang akan kita fokuskan adalah"},
                    {"time": 16, "text": "Body Scan (Pemindaian Tubuh) "},
                    {"time": 19, "text": "Dan Mindful Walking (Berjalan dengan penuh kesadaran)."},
                    {"time": 23, "text": "Sambil mempraktekkan latihan-latihan ini, sadari pikiran, perasaan, dan sensasi apa yang timbul"},
                    {"time": 30, "text": "Ketika sebuah hambatan atau halangan muncul dalam pengalamanmu berlatih.."},
                    {"time": 36, "text": "Mari lihat bagaimana Lisa belajar menggunakan teknik ini.."},
                    {"time": 40, "text": "Aku masih merasakan banyak ketegangan di bagian tubuh"},
                    {"time": 43, "text": "Jadi aku kembali ke Pak Yudhis untuk melakukan pertemuan lanjutan."},
                    {"time": 48, "text": "Ia pun menjelaskan bagaimana Body Scan dapat membantuku.."},
                    {"time": 52, "text": "Menurut Pak Yudhis, body scan merupakan salah satu latihan mindfulness yang akan"},
                    {"time": 58, "text": "Membantuku untuk berlatih menyadari, memberi nama, dan mengamati sensasi-sensasi fisik yang timbul dan hilang pada setiap waktunya."},
                    {"time": 66, "text": "Banyak orang yang menemukan"},
                    {"time": 68, "text": "Bahwa menyadari dan menemukan bagian tubuh yang mengalami ketegangan membantu untuk menghilangkan"},
                    {"time": 74, "text": "Melembutkan, dan membuatnya menjadi lebih rileks…"},
                    {"time": 78, "text": "Seringkali, kita terlalu cepat untuk bereaksi dan mencoba untuk menghilangkan sensasi-sensasi fisik yang kita anggap tidak menyenangkan.."},
                    {"time": 86, "text": "Padahal, dengan menerima berbagai sensasi fisik yang muncul"},
                    {"time": 91, "text": "Kita justru akan belajar bahwa seringkali sensasi-sensasi ini akan hilang dengan sendirinya…"},
                    {"time": 97, "text": "Hal ini pun akan meningkatkan daya tahan kita terhadap pengalaman-pengalaman yang tidak menyenangkan.."},
                    {"time": 103, "text": "Setelah pertemuan dengan Pak Yudhis, aku pun berlatih body scan menggunakan rekaman suara.."},
                    {"time": 109, "text": "Sepertinya menarik mengetahui bagaimana menyadari sensasi yang muncul dari berbagai area tubuhku."},
                    {"time": 116, "text": "Instruksi suaranya membantu, tapi…"}
            ]
            },
            {"src": "assets/audio/sesi 3/3.5 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-3/Ilustrasi 3.5.jpg",
             "transkrip": [
                    {"time": 0, "text": "Pada awalnya, aku merasa aneh.."},
                    {"time": 4, "text": "Hmm..apakah ini wajar?"},
                    {"time": 7, "text": "Bagaimana jika ada sesuatu yang salah?"},
                    {"time": 9, "text": "Mau tidak mau…aku jadi bertanya-tanya…. "},
                    {"time": 12, "text": "Apakah sensasi-sensasi baru ini adalah hal yang wajar…?"},
                    {"time": 16, "text": "Aku pun memutuskan untuk mendengarkan rekaman suaranya hingga selesai.. "},
                    {"time": 20, "text": "Aku berusaha mengikuti arahan untuk menyadari dan mengakui pikiran-pikiranku…"},
                    {"time": 25, "text": "Dan secara perlahan membawa kembali pikiran tersebut ke tubuhku."},
                    {"time": 29, "text": "Butuh beberapa waktu sebelum aku mampu untuk duduk tenang di sepanjang rekaman.."},
                    {"time": 34, "text": "Namun, semakin banyak aku mencoba, semakin lama aku mampu melakukannya.."},
                    {"time": 40, "text": "Ternyata… terasa semakin mudah seiring dengan berjalannya latihan.."},
                    {"time": 44, "text": "Aku bahkan merasa lebih rileks.."},
                    {"time": 46, "text": "Setelah aku merasa lebih percaya diri dengan latihannya"},
                    {"time": 50, "text": "Aku memutuskan untuk mencobanya sendiri."},
                    {"time": 52, "text": "Aku melakukan versi yang lebih singkat di bagian leher dan bahu"},
                    {"time": 56, "text": "Dan menemukan bahwa hal tersebut membantu untuk menenangkanku sebelum tidur.."},
                    {"time": 61, "text": "Aku merasa Mindful Stretching juga sangat berguna untuk mengurangi ketegangan di tubuhku.."},
                    {"time": 66, "text": "Dan aku mulai melakukannya secara rutin dalam keseharian.."},
                    {"time": 70, "text": "Latihan ini membantuku untuk berlatih mindfulness juga."}
            ]
            },
            {"src": "assets/audio/sesi 3/3.6 Damai.mp3", "image": "assets/img/ilustrasi/sesi-3/Ilustrasi 3.6.jpg",
             "transkrip": [
                    {"time": 0, "text": "Menjaga fokus dalam latihan mindfulness memang bukan hal yang mudah.."},
                    {"time": 5, "text": "Lisa menemukan bahwa melakukan latihan Mindful Stretching "},
                    {"time": 9, "text": "Bermanfaat untuk melepaskan ketegangan di tubuhnya"},
                    {"time": 12, "text": "Sehingga lebih siap berlatih mindfulness.."},
                    {"time": 15, "text": "Ia juga menemukan bahwa memulai dengan latihan yang berdurasi lebih singkat"},
                    {"time": 20, "text": "Dan secara bertahap menambahnya, akan berguna"},
                    {"time": 24, "text": "Untuk melakukan latihan yang durasinya lebih panjang.."},
                    {"time": 28, "text": "Temukan strategi yang dapat membantumu untuk mencoba latihan mindfulness.."},
                    {"time": 33, "text": "Hindari adanya hasrat untuk melakukan ‘meditasi dengan benar’"},
                    {"time": 37, "text": "Atau ‘meditasi dengan baik’ atau ‘meditasi dalam waktu yang cukup’"},
                    {"time": 42, "text": "Yang membuatmu justru enggan untuk berlatih."},
                    {"time": 45, "text": "Cara lain untuk berlatih mindfulness adalah melalui gerakan"},
                    {"time": 49, "text": "Salah satunya adalah Mindful Walking"},
                    {"time": 53, "text": "Mindful Walking mengajarkan untuk fokus terhadap berbagai perasaan dan sensasi yang berkaitan dengan gerakan.."},
                    {"time": 59, "text": "Hal tersebut mendorong kita untuk bisa terlibat secara penuh saat berjalan kaki"},
                    {"time": 65, "text": "Mengembangkan rasa ingin tahu"},
                    {"time": 67, "text": "Serta lebih sadar terhadap bagaimana tubuh kita bergerak.."},
                    {"time": 71, "text": "Jika kamu merasa Body Scan agak sulit dan membuatmu menghindar untuk melakukannya"},
                    {"time": 77, "text": "Cobalah mindful walking terlebih dahulu.."},
                    {"time": 80, "text": "Meskipun begitu, baik body scan maupun mindful walking"},
                    {"time": 84, "text": "Merupakan latihan yang penting untuk dipraktekkan dalam mengembangkan keterampilan mindfulness secara berkesinambungan.."},
                    {"time": 91, "text": "Berlatihlah body scan dan mindful walking setidaknya masing-masing 3 kali sebelum materi selanjutnya"},
                    {"time": 97, "text": "Berlatihlah menggunakan panduan rekaman suara terlebih dahulu"},
                    {"time": 102, "text": "Lalu mulailah berlatih beberapa kali tanpa panduan rekaman suara.."},
                    {"time": 106, "text": "Teruslah menambah latihan mindfulness hingga sekitar 20 menit per hari"},
                    {"time": 111, "text": "Dan usahakan untuk tidak melewatkan latihan mindfulness dua hari berturut-turut.."},
                    {"time": 117, "text": "Sekarang…, kamu sudah hampir menyelesaikan Materi 3.."},
                    {"time": 122, "text": "Mari kita rangkum poin-poin pentingnya…"}
            ]
             },
            {"src": "assets/audio/sesi 3/3.7 Damai.mp3", "image": "assets/img/ilustrasi/sesi-3/Ilustrasi 3.7.jpg",
             "transkrip": [
                    {"time": 0, "text": "Sejauh ini, kamu sudah mempelajari bagaimana cara-cara untuk menjadi mindful "},
                    {"time": 6, "text": "Dengan menyadari berbagai sensasi fisik, yaitu melalui body scan…"},
                    {"time": 11, "text": "Menyadari gerakan melalui mindful stretching.."},
                    {"time": 14, "text": "Dan hadir penuh dalam aktivitas sehari-hari seperti makan"},
                    {"time": 18, "text": "Melalui mindful eating, kamu juga sudah berlatih untuk menjadi sadar penuh"},
                    {"time": 23, "text": "Akan pengalamanmu di masa kini, melalui latihan ruang nafas tiga menit.."},
                    {"time": 29, "text": "Maupun latihan mindfulness dalam bernafas"},
                    {"time": 32, "text": "Serta…belajar menjadi mindful saat berjalan kaki melalui mindful walking"},
                    {"time": 40, "text": "Kamu juga telah mempelajari bahwa latihan mindfulness"},
                    {"time": 44, "text": "Mengajarkanmu untuk lebih luwes dalam memberi perhatian…"},
                    {"time": 49, "text": "Untuk bisa membedakan pengalaman primer"},
                    {"time": 51, "text": "Yaitu sesuatu yang ingin kamu fokuskan, seperti nafas, gerakan, aktivitas…"},
                    {"time": 59, "text": "Dari pengalaman sekunder, yang dapat mengalihkan perhatianmu dari apa yang sedang kamu fokuskan…"},
                    {"time": 65, "text": "Ini akan membutuhkan latihan dan kesabaran"},
                    {"time": 69, "text": "Jadi bersikaplah lembut terhadap dirimu sendiri, dan akui kerja kerasmu"},
                    {"time": 76, "text": "Di sesi ini, kamu juga telah mempelajari tentang lima hambatan umum dalam praktik mindfulness"},
                    {"time": 83, "text": "Seperti hasrat, keengganan, rasa kantuk, kegelisahan, dan keraguan.."},
                    {"time": 92, "text": "Kamu perlu menyadari kapan pengalaman-pengalaman ini muncul"},
                    {"time": 96, "text": "Baik dalam keseharianmu ataupun dalam praktik mindfulness yang kamu lakukan.."},
                    {"time": 101, "text": "Dan di sesi terakhir, kami akan mengulas apa yang telah kami bahas di dalam materi sejauh ini"},
                    {"time": 108, "text": "Dan bagaimana caranya untuk terus membangun dan memperluas keterampilan mindfulness.."},
                    {"time": 113, "text": "Terima kasih sudah membaca Materi 3."},
                    {"time": 116, "text": "Materi 4 akan tersedia dalam 5 hari ke depan."},
                    {"time": 120, "text": "Mohon menjadwalkan waktu untuk menyelesaikan Materi 4."},
                    {"time": 123, "text": "Jangan lupa untuk mengunduh ringkasan materi dan rekaman suara latihan mindfulness sebelum kamu pergi.."},
                    {"time": 129, "text": "Kami berharap untuk segera bertemu kamu kembali di sesi keempat"},
                    {"time": 133, "text": "Yang merupakan sesi terakhir dari program intervensi ini."},
                    {"time": 137, "text": "Sampai berjumpa di sesi selanjutnya!"}
            ]
            }
        ],
        "naskah": "assets/ringkasan_materi/Ringkasan Sesi 3 - Psidamai.pdf"
    },
    "4": {
        "judul": "Sesi 4 - Mindfulness dalam Keseharian",
        "deskripsi": """Mindfulness dalam keseharian: "Mindfulness Dalam Keseharian" adalah bagian dari program mindfulness untuk mahasiswa, berfokus pada penerapan mindfulness dalam kehidupan sehari-hari. Pada sesi ini, peserta didorong untuk melihat kembali perkembangan mereka dalam praktik mindfulness, seperti mengenali dan menerima pengalaman tanpa menghakimi serta mengelola ketidaknyamanan dengan cara yang lebih sadar.
        Sesi ini juga menekankan pentingnya memiliki pandangan realistis tentang proses pembelajaran mindfulness dan mengajak peserta untuk bersikap welas asih terhadap diri sendiri. Program ini menutup dengan pesan bahwa mindfulness adalah keterampilan yang perlu dilatih terus-menerus agar dapat meningkatkan kesejahteraan dan ketahanan diri terhadap tekanan sehari-hari.""",
        "judul_audio1": "Audio mindfulness untuk Ketidaknyaman Fisik",
        "audio1": "assets/audio panduan/Psidamai 4.  Mindfulness for Physical Discomfort.mp3",
        "judul_audio2": "Audio mindfulness untuk Menghadapi Kesulitan",
        "audio2": "assets/audio panduan/Psidamai 4. Mindfulness for Difficulties.mp3",
        "audio": [
            {"src": "assets/audio/sesi 4/4.1 Damai.mp3", "image": "assets/img/ilustrasi/sesi-4/Ilustrasi 4.1.jpg",
             "transkrip": [
                    {"time": 0, "text": "Selamat datang di Materi 4!"},
                    {"time": 2, "text": "Ini adalah materi terakhir di dalam Program Perkenalan Mindfulness untuk Mahasiswa."},
                    {"time": 8, "text": "Senang bertemu kembali!"},
                    {"time": 10, "text": "Kami harap kamu sudah mempraktekkan keterampilan-keterampilan yang telah kamu pelajari di tiga materi sebelumnya"},
                    {"time": 17, "text": "Sebelum kita mulai materi ini"},
                    {"time": 19, "text": "Mari kita melakukan kilas balik akan perkembangan yang telah kamu capai sejak memulai program ini."},
                    {"time": 25, "text": "Kamu bisa bertanya kepada dirimu sendiri.."},
                    {"time": 28, "text": "Apakah ada hal yang terasa berbeda?"},
                    {"time": 31, "text": "Apa saja yang telah kamu capai sejauh ini? ….."},
                    {"time": 33, "text": "Lalu, apa saja yang telah kamu pelajari?"},
                    {"time": 38, "text": "Penting untuk mengenali keberhasilanmu"},
                    {"time": 40, "text": "Baik kecil maupun besar, dan bersabarlah dengan kemajuanmu dalam berlatih."},
                    {"time": 46, "text": "Mempelajari keterampilan baru memang tidak mudah."},
                    {"time": 49, "text": "Tidak jarang, motivasi yang datang sifatnya pasang surut."},
                    {"time": 54, "text": "Ini adalah proses yang normal, yang penting kamu terus belajar untuk maju."},
                    {"time": 61, "text": "Sejauh ini, kamu telah mendapatkan banyak informasi."},
                    {"time": 65, "text": "Pertama, tentang mengenali bagaimana pikiranmu bekerja"},
                    {"time": 70, "text": "Kedua, menyadari, menamai, dan mengamati bagian-bagian yang berbeda dari pengalamanmu saat ini…"},
                    {"time": 77, "text": "Dan Ketiga, memusatkan perhatian pada momen ‘di sini dan saat ini’ "},
                    {"time": 83, "text": "Dengan menggunakan beberapa jangkar"},
                    {"time": 85, "text": "Seperti nafas"},
                    {"time": 86, "text": "Area tubuh"},
                    {"time": 87, "text": "Sensasi fisik"},
                    {"time": 89, "text": "Gerakan"},
                    {"time": 90, "text": "Maupun berbagai sensasi indra"},
                    {"time": 92, "text": "Baik sentuhan, aroma, penglihatan, pendengaran, dan rasa"},
                    {"time": 101, "text": "Kamu juga sudah belajar untuk mengenali hambatan umum dalam berlatih mindfulness"},
                    {"time": 106, "text": "Seperti hasrat, keengganan, rasa kantuk, kegelisahan, dan keraguan, serta bagaimana cara mengatasinya."},
                    {"time": 116, "text": "Selain itu, kamu sudah mempelajari bahwa penting untuk selalu menanamkan sikap penuh rasa ingin tahu"},
                    {"time": 124, "text": "Dan tidak menghakimi dalam menyadari berbagai yang terjadi.."},
                    {"time": 128, "text": "Baik yang terjadi di dalam pikiran, tubuh, dan lingkungan…"},
                    {"time": 133, "text": "Dari waktu demi waktu, pada momen “di sini dan saat ini”"},
                    {"time": 140, "text": "Selain itu, penting juga untuk selalu menunjukkan kebaikan dan welas asih kepada diri sendiri"},
                    {"time": 147, "text": "Dan berlatih untuk bersabar dengan diri sendiri"}
            ]
            },
            {"src": "assets/audio/sesi 4/4.2 Damai.mp3", "image": "assets/img/ilustrasi/sesi-4/Ilustrasi 4.2.jpg",
             "transkrip": [
                    {"time": 0, "text": "Latihan berikutnya yang ingin kami kenalkan di sesi ini adalah"},
                    {"time": 5, "text": "Mindfulness untuk Mengatasi Ketidaknyamanan."},
                    {"time": 10, "text": "Kamu bisa mendengarkan rekaman audio yang memandumu berlatih di akhir materi."},
                    {"time": 16, "text": "Latihan ini akan memandu kamu untuk menyadari seberapa cepat dan otomatis"},
                    {"time": 21, "text": "Bahwa kita seringkali bereaksi terhadap pengalaman yang tidak menyenangkan."},
                    {"time": 26, "text": "Latihan tersebut akan membantu juga untuk belajar"},
                    {"time": 30, "text": "Bagaimana menoleransi adanya dorongan untuk bersikap reaktif…"},
                    {"time": 34, "text": "Dan bagaimana untuk merespon secara lebih mindful terhadap pengalaman tersebut."},
                    {"time": 40, "text": "Mindfulness untuk Mengatasi Ketidaknyamanan mencakup:"},
                    {"time": 45, "text": "Satu, melakukan body scan pada area yang terasa tidak nyaman dalam tingkat ringan dan sedang"},
                    {"time": 50, "text": "Seperti rasa nyeri ringan, perasaan tidak nyaman, rasa gatal, dan…"},
                    {"time": 56, "text": "Kedua, mengamati bahwa dorongan untuk menghilangkan ketidaknyamanan"},
                    {"time": 60, "text": "Tersebut dapat muncul, menguat, dan pergi, tanpa kita harus bereaksi terhadapnya."},
                    {"time": 68, "text": "Pada dasarnya, kita memang seringkali terdorong untuk bereaksi dengan cepat"},
                    {"time": 73, "text": "Dan ingin menghilangkan sesuatu yang tidak menyenangkan, tidak nyaman, atau tidak diinginkan."},
                    {"time": 80, "text": "Namun, izinkanlah berbagai pikiran, perasaan, dan sensasi itu hadir…"},
                    {"time": 86, "text": "Tanpa harus melawan, mencoba untuk mengatur, atau bahkan menekannya."},
                    {"time": 93, "text": "Hal itu akan membantu kita untuk menjadi lebih sabar dan toleran, berpikir jernih, dan merasa stabil… tanpa harus merasa kewalahan"},
                    {"time": 102, "text": "Kamu akan menyadari bahwa perasaan dan sensasi"},
                    {"time": 106, "text": "Semuanya datang dan pergi, timbul, menguat, dan akan mereda pada waktunya."},
                    {"time": 114, "text": "Segala yang terjadi bukanlah sesuatu yang statis, namun dinamis, dan selalu berubah."},
                    {"time": 122, "text": "Selanjutnya, kamu akan menemukan informasi lainnya mengenai hal ini pada ringkasan materi"},
                    {"time": 128, "text": "Kami menganjurkan untuk meluangkan waktu lebih banyak untuk materi ini."},
                    {"time": 133, "text": "Penting untuk menjadi realistis tentang durasi waktu yang akan diperlukan"},
                    {"time": 137, "text": "Untuk mengembangkan dan menguasai keterampilan-keterampilan ini…"},
                    {"time": 141, "text": "Dan untuk secara rutin meluangkan waktu berlatih."},
                    {"time": 145, "text": "Nah, mari sekarang kita lihat bagaimana keadaan Lisa."}
            ]
            },
            {"src": "assets/audio/sesi 4/4.3 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-4/Ilustrasi 4.3.jpg",
             "transkrip": [
                    {"time": 0, "text": "Meskipun aku sudah memahami prinsip-psinsip mindfulness dan apa yang perlu aku lakukan untuk berlatih"},
                    {"time": 7, "text": "kadangkala ada saja hal-hal yang menghalangi..."},
                    {"time": 10, "text": "Aku sering lupa untuk berlatih dan sulit sekali untuk meluangkan waktu.. "},
                    {"time": 14, "text": "Aku lalu merasa bersalah karena tidak latihan..."},
                    {"time": 18, "text": "Ketika aku merasa patah semangat dan banyak masalah menghampiri hidupku"},
                    {"time": 23, "text": "aku kadangkala bertanya-tanya bagaimana menjadi mindful dapat membantu..."},
                    {"time": 28, "text": "Pun di saat aku mencoba untuk lebih hadir, fokus, dan tidak menghakimi"},
                    {"time": 33, "text": "justru muncul pikiran bahwa aku telah gagal"},
                    {"time": 36, "text": "dan melakukan semuanya dengan cara yang salah.."},
                    {"time": 39, "text": "Aku pun bercerita kepada Pak Yudhis mengenai kesulitanku dalam latihan."},
                    {"time": 44, "text": "Ia mengingatkan aku untuk berhati-hati dengan adanya kemungkinan munculnya hambatan dalam berlatih."},
                    {"time": 51, "text": "Ia mengingatkan sekali lagi bahwa tidak ada cara yang benar atau salah untuk menjadi mindful."},
                    {"time": 59, "text": "Aku pun merenung… dan tersadarkan bahwa selama latihan"},
                    {"time": 64, "text": "rasanya seperti ada keinginan yang kuat untuk menghindari kesulitan..."},
                    {"time": 68, "text": "Jadi, bukan pikiranku yang menjadikan itu sulit"},
                    {"time": 72, "text": "tapi hasrat di dalam diriku untuk menjadi ‘sempurna’ saat berlatih mindfulness."},
                    {"time": 78, "text": "Aku terlalu ingin untuk benar-benar fokus, sabar, dan mengamati apa yang muncul dalam pikiranku..."},
                    {"time": 86, "text": "Tapi aku menyadari bahwa setiap kali aku berjuang untuk mencapai latihan yang sempurna seperti itu"},
                    {"time": 96, "text": "banyak perasaan dan sensasi fisik yang muncul.."},
                    {"time": 102, "text": "Aku juga menyadari bahwa hasrat untuk melakukan sesuatu dengan sempurna tidak hanya mempengaruhi latihanku"},
                    {"time": 104, "text": "Tapi itu juga membuatku merasa benar-benar tertekan ketika menyelesaikan semua tugas"},
                    {"time": 110, "text": "Setiap kali hal-hal menjadi tidak seperti apa yang aku inginkan"},
                    {"time": 114, "text": "aku akan merasa khawatir dan terus mencoba untuk membuatnya lebih baik."},
                    {"time": 119, "text": "Namun, semakin aku bereaksi terhadap keinginan ini, semakin aku merasa tertekan.."},
                    {"time": 125, "text": "Latihan mindfulness sangat membantu untuk ‘melihat’ siklus ini.."},
                    {"time": 129, "text": "Jadi, aku pun kembali pada latihan dasar"},
                    {"time": 133, "text": "berlatih untuk menamai apa yang muncul di dalam pikiran dan tubuhku."},
                    {"time": 138, "text": "Namun, kali ini aku tidak berusaha berhenti dan menunda latihan"},
                    {"time": 143, "text": "atau bereaksi terhadap perasaan frustrasi yang muncul.."},
                    {"time": 147, "text": "Aku mendorong diri untuk tetap bertahan"},
                    {"time": 150, "text": "menamai perasaan dan sensasi yang muncul"},
                    {"time": 153, "text": "dan pelan-pelan membawa kembali pikiranku kembali pada nafas.."},
                    {"time": 158, "text": "Aku hanya perlu untuk berlatih menjadi lebih sabar terhadap diri aku sendiri..."},
                    {"time": 164, "text": "“Hmm… Ada rasa nyeri di punggungku….”"},
                    {"time": 167, "text": "“Tanganku terasa hangat..”"},
                    {"time": 169, "text": "“Oke, pikiran-pikiran mulai muncul..” "},
                    {"time": 173, "text": "“Tarik nafas...”"}
            ]
            },
            {"src": "assets/audio/sesi 4/4.4 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-4/Ilustrasi 4.4.jpg",
             "transkrip": [
                    {"time": 0, "text": "Aku juga berlatih untuk mulai berfokus tidak hanya pada nafas"},
                    {"time": 5, "text": "namun mencoba untuk menjadi mindful pada semua rasa lain yang aku rasakan...."},
                    {"time": 10, "text": "Rasanya lebih mudah dan membantu untuk mendapatkan kepercayaan diri."},
                    {"time": 15, "text": "“Hmm… Aku dapat merasakan hangatnya ruangan di wajahku... Aku menyadari munculnya keraguan, dan itu tidak masalah…”"},
                    {"time": 24, "text": "Dibandingkan memaksakan diri untuk melakukan latihan yang lama"},
                    {"time": 28, "text": "aku mempraktekkan latihan mindfulness yang lebih singkat setiap harinya.."},
                    {"time": 33, "text": "Aku melakukan ruang bernafas tiga menit tiap kali aku akan mulai kuliah atau mengerjakan tugasku.."},
                    {"time": 41, "text": "Ketika aku mengakui dan melepaskan penghalang-penghalang seperti hasrat"},
                    {"time": 45, "text": "keengganan"},
                    {"time": 47, "text": "dan keraguan"},
                    {"time": 48, "text": "rasanya menjadi lebih mudah untuk mindful dan terlibat lebih sering di sepanjang hariku…"},
                    {"time": 54, "text": "Aku menyadari bahwa aku juga sangat menikmati latihan mindfulness di ruang terbuka.."},
                    {"time": 60, "text": "Aku akan mendengarkan suara-suara di sekitarku dan memperhatikan bagaimana rasanya tubuhku..."},
                    {"time": 67, "text": "Aku tidak selalu harus fokus pada nafasku"},
                    {"time": 70, "text": "Dan aku dapat hadir “disini dan saat ini” dengan cara yang lain."},
                    {"time": 75, "text": "Aku membagi pengalamanku dengan Aisyah"},
                    {"time": 77, "text": "Dan kami memutuskan untuk melakukan latihan mindfulness singkat bersama-sama sepanjang hari"},
                    {"time": 83, "text": "Seperti makan dengan mindful saat makan siang"},
                    {"time": 86, "text": "Atau melakukan body scan singkat setelah selesai berkuliah.."},
                    {"time": 91, "text": "Ketika aku melepaskan keinginan untuk menjadi mindful dengan cara tertentu"},
                    {"time": 95, "text": "Rasanya menjadi lebih mudah dan tidak begitu membebani untuk menggunakannya dalam kehidupan aku sehari-hari."}
            ]
            },
            {"src": "assets/audio/sesi 4/4.5 Damai.mp3", "image": "assets/img/ilustrasi/sesi-4/Ilustrasi 4.5.jpg",
             "transkrip": [
                    {"time": 0, "text": "Dan aku berlatih untuk memfokuskan perhatian penuh "},
                    {"time": 4, "text": "Dan menjadi lebih terlibat dalam apa yang sedang aku lakukan sepanjang hari..."},
                    {"time": 9, "text": "seperti misalnya menjadi lebih hadir saat bersama dengan orangtuaku.."},
                    {"time": 16, "text": "Aku mulai merasa lebih tenang dan fokus dalam keseharian"},
                    {"time": 20, "text": "Dan aku menyadari diriku terasa lebih sadar penuh, dan pikiranku menjadi lebih jernih.. "},
                    {"time": 25, "text": "Aku berlatih untuk selalu hadir dalam apa yang sedang aku lakukan. "},
                    {"time": 30, "text": "Pikiran-pikiran yang bersifat menghakimi kadangkala masih tetap datang"},
                    {"time": 34, "text": "namun aku tidak bereaksi terhadapnya, karena aku sadar.."},
                    {"time": 38, "text": "segalanya akan datang dan pergi."},
                    {"time": 41, "text": "Aku mulai menikmati waktu-waktu tertentu di dalam hariku ketika aku menjadi lebih hadir dan terlibat."},
                    {"time": 48, "text": "Situasi penuh tekanan akan muncul kapan saja"},
                    {"time": 51, "text": "namun daripada terlarut di dalamnya dan merasa kewalahan"},
                    {"time": 55, "text": "aku belajar untuk menjadi mindful terhadap tubuhku…"},
                    {"time": 59, "text": "Mengarahkan nafas pada area tubuh yang tegang"},
                    {"time": 62, "text": "atau sensasi yang tidak nyaman"},
                    {"time": 64, "text": "sambil tetap fokus pada apa yang sedang aku lakukan"},
                    {"time": 68, "text": "Daripada mengalihkan diri atau mencoba untuk “melamun” dan melupakan masalah"},
                    {"time": 73, "text": "Aku mulai lebih terlibat di dalam semua hal lain yang menyenangkan hariku"},
                    {"time": 77, "text": "dan itu membantu mengurangi stress yang aku rasakan.."}
            ]
            },
            {"src": "assets/audio/sesi 4/4.6 Lisa.mp3", "image": "assets/img/ilustrasi/sesi-4/Ilustrasi 4.6.jpg",
             "transkrip": [
                    {"time": 0, "text": "Semua kerja keras yang aku lakukan dalam berlatih untuk hadir di saat ini mulai memberi hasil."},
                    {"time": 7, "text": "Rasanya menjadi lebih mudah bagiku untuk berada “disini dan saat ini”"},
                    {"time": 11, "text": "daripada secara terus menerus terjebak dalam pikiranku.."},
                    {"time": 15, "text": "Hal ini membantuku untuk lebih terlibat dengan hal-hal yang benar-benar penting untukku, seperti keluarga dan studiku."},
                    {"time": 24, "text": "Belajar tentang mindfulness dan mengembangkan keterampilan baru "},
                    {"time": 28, "text": "membantuku untuk menjadi lebih tenang dan lebih menikmati hal-hal kecil di hidupku."},
                    {"time": 33, "text": "Mudah merasa marah..ingin melampiaskan pada orang-orang di sekitar…"},
                    {"time": 38, "text": "Aku menemukan diriku menjadi lebih resilien terhadap tekanan hidup sehari-hari"},
                    {"time": 44, "text": "sehingga membuatku lebih memiliki energi untuk mengatasi masalah-masalah yang lebih besar"},
                    {"time": 51, "text": "Dan hal tersebut membantu aku belajar untuk memperlakukan diriku secara lebih baik."},
                    {"time": 58, "text": "Aku menemukan bahwa diriku menjadi tidak terlalu kritis maupun merasa frustrasi dengan diri sendiri."},
                    {"time": 61, "text": "Terima kasih sudah mengikuti ceritaku.."},
                    {"time": 66, "text": "Aku tahu kamu mungkin tidak merasa terhubung dengan semua bagian dari cerita ini"},
                    {"time": 70, "text": "namun aku harap kamu mendapatkan manfaatnya."},
                    {"time": 74, "text": "Aku harap kamu telah belajar dari pengalamanku juga, dan semoga kamu bisa melakukan latihanmu dengan baik! "}
            ]
            },
            {"src": "assets/audio/sesi 4/4.7 Damai.mp3", "image": "assets/img/ilustrasi/sesi-4/Ilustrasi 4.7.jpg",
             "transkrip": [
                    {"time": 0, "text": "Sebelum saya menutup sesi ini, perlu selalu diingat bahwa…"},
                    {"time": 6, "text": "Mindfulness bukanlah Aktivitas ‘melamun’ atau melarikan diri dari kenyataan"},
                    {"time": 13, "text": "Strategi relaksasi"},
                    {"time": 15, "text": "Keadaan supranatural"},
                    {"time": 18, "text": "Cara untuk menghindari masalah"},
                    {"time": 20, "text": "atau Perbaikan instan dan solusi ajaib terhadap kesulitan."},
                    {"time": 26, "text": "Mindfulness adalah keadaan pikiran yang terbuka"},
                    {"time": 31, "text": "sadar dan penuh rasa ingin tahu"},
                    {"time": 34, "text": "Keterampilan yang bisa dipelajari melalui latihan rutin"},
                    {"time": 38, "text": "Bentuk khusus dari memberi perhatian dan kesadaran"},
                    {"time": 42, "text": "Cara lain untuk terhubung dengan kesulitan atau masalah yang dialami"},
                    {"time": 47, "text": "Serta cara untuk menjadi hadir dan terlibat di dalam semua aspek dalam kehidupan."},
                    {"time": 55, "text": "Kami harap"},
                    {"time": 56, "text": "kamu telah mempelajari beberapa keterampilan yang bermanfaat di sepanjang kursus ini"},
                    {"time": 62, "text": "Kami juga berharap kamu merasa lebih percaya diri dalam menggunakan mindfulness di dalam keseharian."},
                    {"time": 70, "text": "Ada begitu banyak informasi yang sudah kami berikan…"},
                    {"time": 74, "text": "Kami menganjurkan kamu untuk membaca ulang materi-materinya"},
                    {"time": 77, "text": "dan tinjau lagi ringkasan materi di minggu-minggu selanjutnya."},
                    {"time": 84, "text": "Selamat, kamu telah menyelesaikan materi terakhir dari Program Perkenalan Mindfulness untuk Mahasiswa!"},
                    {"time": 89, "text": "Ingatlah untuk mengunduh ringkasan materi sebelum kamu pergi."},
                    {"time": 93, "text": "Kami mengharapkan yang terbaik untukmu di masa depan"},
                    {"time": 96, "text": "dan terima kasih telah mengikuti program ini!"}
            ]
            },
        ],
        "naskah": "assets/ringkasan_materi/Ringkasan Sesi 4 - Psidamai.pdf"
    },

}


@program_details_.route("/materi/<int:materi_id>")
def materi_details(materi_id):
    materi_key = str(materi_id)
    materi = materi_data.get(materi_key)
    myToken = request.cookies.get("mytoken")
    SECRET_KEY = current_app.config['SECRET_KEY']
    try:
        payload = jwt.decode(myToken, SECRET_KEY, algorithms=["HS256"])
        user_info = current_app.db.users.find_one({"username": payload["id"]})
        if materi:
            return render_template("dashboard/program_details.html", materi=materi, user_info=user_info)
        else:
            return "Materi tidak ditemukan", 404
    except jwt.ExpiredSignatureError:
        return redirect(url_for("home.menu"))
    except jwt.exceptions.DecodeError:
        return redirect(url_for("home.menu"))

@program_details_.route('/save-status',  methods=["POST"])
def save_status():
    email = request.form['email']
    program = "Perkenalan Mindfullness Untuk Mahasiswa"
    materi = request.form['materi']
    status = request.form['status']
    riwayat = datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    tanggal = datetime.now().strftime("%d-%m-%Y")
    waktu = datetime.now().strftime("%H:%M:%S")
    doc = {       
        "email": email, 
         "program": program,
          "materi": materi,
           "status": status,
            "riwayat": riwayat,
             "tanggal": tanggal,
              "waktu": waktu                                                
    }
    exists = bool(current_app.db.status.find_one({"email": email, "materi":materi}))
    if exists:
        return jsonify(
            {
                "exists": exists,
                "result": "Sudah Selesai",
                "msg": "Program telah diselesaikan!",
            }
        )
    else:
        current_app.db.status.insert_one(doc)
        return jsonify(
            {
                "exists": exists,
                "result": "Succes",
                "msg": "Program telah diselesaikan!",
            }
        )
        
    

# Define Blueprint in the main app
def create_app():
    app = Flask(__name__)
    app.register_blueprint(program_details_, url_prefix='/program_details')
    return app